<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Processed Payments Print</title>
    <style>
        @page { size: landscape; margin: 10mm; }
        * { box-sizing: border-box; }
        body { margin: 0; font-family: "Segoe UI", Arial, sans-serif; color: #111827; background: #fff; }

        .print-header { border-bottom: 2px solid #1a5f7a; padding-bottom: 8px; margin-bottom: 10px; }
        .print-header-grid { display: table; width: 100%; }
        .print-header-left, .print-header-right { display: table-cell; vertical-align: top; }
        .print-header-left { width: 60%; }
        .print-header-right { width: 40%; text-align: right; font-size: 10px; color: #475569; }
        .brand { font-size: 24px; font-weight: 700; color: #0f172a; }
        .doc-title { margin-top: 6px; font-size: 16px; font-weight: 700; color: #0f172a; }
        .meta { margin-top: 2px; font-size: 10px; color: #64748b; }

        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; break-inside: avoid; }
        th, td { border: 1px solid #d1d5db; padding: 5px; vertical-align: top; font-size: 9px; word-break: break-word; overflow-wrap: anywhere; }
        th { background: #1a5f7a; color: #fff; text-transform: uppercase; letter-spacing: 0.02em; font-size: 8px; text-align: left; }
        tbody tr:nth-child(even) td { background: #f8fafc; }
        .amount { text-align: right; font-weight: 700; }

        .footer { margin-top: 8px; display: flex; justify-content: space-between; align-items: center; font-size: 8px; color: #6b7280; font-style: italic; }
        .page-count::after { content: "Page " counter(page) " of " counter(pages); font-style: normal; }

        .status-pill { display: inline-block; border-radius: 999px; padding: 2px 7px; font-size: 8px; font-weight: 700; text-transform: uppercase; }
        .status-posted, .status-processed { background: #dcfce7; color: #166534; }
        .status-other { background: #fef3c7; color: #92400e; }
    </style>
</head>
<body>
    <header class="print-header">
        <div class="print-header-grid">
            <div class="print-header-left">
                <div class="brand">Gaitho Loans</div>
                <div class="doc-title">PROCESSED PAYMENTS LEDGER</div>
                <div class="meta">Branch: {{ $branchName }}</div>
            </div>
            <div class="print-header-right">
                <div>Generated: {{ $generatedAt->format('M j, Y g:i A') }}</div>
                <div>Generated by: {{ $generatedBy }}</div>
                <div>System: Kenya</div>
            </div>
        </div>
    </header>

    <main>
        <table>
            <thead>
                <tr>
                    <th style="width: 14%;">Transaction</th>
                    <th style="width: 9%; text-align:right;">Amount</th>
                    <th style="width: 26%;">Payment Details</th>
                    <th style="width: 14%;">Client</th>
                    <th style="width: 20%;">Message</th>
                    <th style="width: 9%;">Approval</th>
                    <th style="width: 8%;">Time</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($payments as $p)
                    @php
                        $status = strtolower((string) ($p->status ?? 'processed'));
                        $statusClass = in_array($status, ['posted', 'processed'], true) ? 'status-posted' : 'status-other';
                        $rowBreakdown = $processedBreakdowns[$p->id] ?? [];
                        $principalAmount = (float) ($rowBreakdown['principal'] ?? 0.0);
                        $interestAmount = (float) ($rowBreakdown['interest'] ?? 0.0);
                        $feesAmount = (float) ($rowBreakdown['fees'] ?? 0.0);
                        $penaltyAmount = (float) ($rowBreakdown['penalty'] ?? 0.0);
                        $overpaymentAmount = (float) ($rowBreakdown['overpayment'] ?? 0.0);
                        $hasAllocationData = (bool) ($rowBreakdown['has_allocation_data'] ?? false);
                        $fallbackMessage = $rowBreakdown['fallback_message'] ?? null;
                        $allocationMismatch = (bool) ($rowBreakdown['allocation_mismatch'] ?? false);
                    @endphp
                    <tr>
                        <td>{{ $p->reference ?? '—' }}</td>
                        <td class="amount">{{ $p->currency }} {{ number_format((float) $p->amount, 2) }}</td>
                        <td>
                            @if ($allocationMismatch)
                                <span class="status-pill status-other" style="margin-bottom:4px;display:inline-block;">Allocation mismatch</span>
                            @endif
                            <ul style="margin:0; padding-left:14px;">
                                @if ($hasAllocationData)
                                    @if ($principalAmount > 0)
                                        <li>Principal - {{ number_format($principalAmount, 2) }}</li>
                                    @endif
                                    @if ($interestAmount > 0)
                                        <li>Interest - {{ number_format($interestAmount, 2) }}</li>
                                    @endif
                                    @if ($feesAmount > 0)
                                        <li>Fees - {{ number_format($feesAmount, 2) }}</li>
                                    @endif
                                    @if ($penaltyAmount > 0)
                                        <li>Penalty - {{ number_format($penaltyAmount, 2) }}</li>
                                    @endif
                                    @if ($overpaymentAmount > 0)
                                        <li>Overpayment - {{ number_format($overpaymentAmount, 2) }}</li>
                                    @endif
                                @elseif ($fallbackMessage)
                                    <li style="list-style:none;margin-left:-14px;color:#92400e;">{{ $fallbackMessage }}</li>
                                @endif
                                @if ($p->mpesa_receipt_number)
                                    <li>Receipt - {{ $p->mpesa_receipt_number }}</li>
                                @endif
                            </ul>
                        </td>
                        <td>
                            {{ $p->loan?->loanClient?->full_name ?? '—' }}
                            <div style="color:#64748b;">{{ $p->loan?->loanClient?->id_number ?? '—' }}</div>
                        </td>
                        <td>{{ $p->message ?? '—' }}</td>
                        <td>
                            <span class="status-pill {{ $statusClass }}">{{ $status }}</span>
                            <div style="margin-top:3px;">{{ $p->validatedByUser?->name ?? $p->postedByUser?->name ?? 'System' }}</div>
                        </td>
                        <td>{{ optional($p->transaction_at)->format('h:i a') ?? '—' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" style="text-align:center; color:#64748b;">No processed payments yet.</td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="1" style="font-weight:700;">Grand Total</td>
                    <td class="amount" style="font-weight:700;">KES {{ number_format((float) $totalAmount, 2) }}</td>
                    <td colspan="5"></td>
                </tr>
            </tfoot>
        </table>
    </main>

    <footer class="footer">
        <span>This is a system-generated print view for operational reconciliation.</span>
        <span class="page-count"></span>
    </footer>

    <script>
        window.onload = function () { window.print(); };
    </script>
</body>
</html>
