<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Unposted Payments Print</title>
    <style>
        @page { size: landscape; margin: 10mm; }
        body { margin: 0; font-family: "Segoe UI", Arial, sans-serif; color: #111827; background: #fff; }
        * { box-sizing: border-box; }

        .print-header { border-bottom: 2px solid #1a5f7a; padding-bottom: 8px; margin-bottom: 10px; }
        .header-grid { display: table; width: 100%; }
        .left, .right { display: table-cell; vertical-align: top; }
        .left { width: 60%; }
        .right { width: 40%; text-align: right; font-size: 10px; color: #475569; }
        .brand { font-size: 24px; font-weight: 700; color: #0f172a; }
        .title { margin-top: 6px; font-size: 16px; font-weight: 700; color: #0f172a; }
        .meta { margin-top: 2px; font-size: 10px; color: #64748b; }

        table { width: 100%; border-collapse: collapse; table-layout: fixed; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; break-inside: avoid; }
        th, td { border: 1px solid #d1d5db; padding: 5px; vertical-align: top; font-size: 9px; word-break: break-word; overflow-wrap: anywhere; }
        th { background: #1a5f7a; color: #fff; text-transform: uppercase; letter-spacing: 0.02em; font-size: 8px; text-align: left; }
        tbody tr:nth-child(even) td { background: #f8fafc; }
        .amount { text-align: right; font-weight: 700; }
        .ref { font-weight: 700; color: #1e3a8a; }
        .status-pill { display: inline-block; border-radius: 999px; padding: 2px 7px; font-size: 8px; font-weight: 700; text-transform: uppercase; }
        .status-unposted, .status-unmatched { background: #fef3c7; color: #92400e; }
        .status-other { background: #e2e8f0; color: #334155; }

        .footer { margin-top: 8px; display: flex; justify-content: space-between; align-items: center; font-size: 8px; color: #6b7280; font-style: italic; }
        .page-count::after { content: "Page " counter(page) " of " counter(pages); font-style: normal; }
    </style>
</head>
<body>
    <header class="print-header">
        <div class="header-grid">
            <div class="left">
                <div class="brand">Gaitho Loans</div>
                <div class="title">UNPOSTED PAYMENTS QUEUE</div>
                <div class="meta">Branch: {{ $branchName }}</div>
            </div>
            <div class="right">
                <div>Generated: {{ $generatedAt->format('M j, Y g:i A') }}</div>
                <div>Generated by: {{ $generatedBy }}</div>
                <div>System: Kenya</div>
            </div>
        </div>
    </header>

    <main>
        <table>
            <thead>
                <tr>
                    <th style="width: 12%;">Reference</th>
                    <th style="width: 10%;">Loan</th>
                    <th style="width: 14%;">Client</th>
                    <th style="width: 10%; text-align:right;">Amount</th>
                    <th style="width: 10%;">Channel</th>
                    <th style="width: 14%;">Status</th>
                    <th style="width: 11%;">When</th>
                    <th style="width: 10%;">Payer #</th>
                    <th style="width: 9%;">Receipt</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($payments as $p)
                    @php
                        $channel = strtolower((string) ($p->channel ?? ''));
                        $status = str_contains($channel, 'unmatched') ? 'unmatched' : strtolower((string) ($p->status ?? 'unposted'));
                        $statusClass = in_array($status, ['unposted', 'unmatched'], true) ? 'status-unposted' : 'status-other';
                    @endphp
                    <tr>
                        <td class="ref">{{ $p->reference ?? '—' }}</td>
                        <td>{{ $p->loan?->loan_number ?? '—' }}</td>
                        <td>{{ $p->loan?->loanClient?->full_name ?? '—' }}</td>
                        <td class="amount">{{ $p->currency }} {{ number_format((float) $p->amount, 2) }}</td>
                        <td>{{ $p->channel ?? '—' }}</td>
                        <td><span class="status-pill {{ $statusClass }}">{{ $status ?: 'unknown' }}</span></td>
                        <td>{{ optional($p->transaction_at)->format('Y-m-d H:i') ?? '—' }}</td>
                        <td>{{ $p->payer_msisdn ?? '—' }}</td>
                        <td>{{ $p->mpesa_receipt_number ?? '—' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="9" style="text-align:center; color:#64748b;">No unposted payments found.</td>
                    </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" style="font-weight:700;">Grand Total</td>
                    <td class="amount" style="font-weight:700;">KES {{ number_format((float) $totalAmount, 2) }}</td>
                    <td colspan="5"></td>
                </tr>
            </tfoot>
        </table>
    </main>

    <footer class="footer">
        <span>This is a system-generated print view for operational reconciliation.</span>
        <span class="page-count"></span>
    </footer>

    <script>
        window.onload = function () { window.print(); };
    </script>
</body>
</html>
