<?php

use App\Support\Property\PropertyWorkspaceTabs;
use App\Http\Controllers\Property\Agent\AgentPublicListingController;
use App\Http\Controllers\Property\Agent\AgentWorkspaceFormController;
use App\Http\Controllers\Property\Agent\DashboardController;
use App\Http\Controllers\Property\Agent\FinancialsController;
use App\Http\Controllers\Property\Agent\PerformanceWorkspaceController;
use App\Http\Controllers\Property\Agent\PmForwarderTokenController;
use App\Http\Controllers\Property\Agent\PmInvoiceController;
use App\Http\Controllers\Property\Agent\PmLeaseWebController;
use App\Http\Controllers\Property\Agent\PmMaintenanceWebController;
use App\Http\Controllers\Property\Agent\PmPaymentController;
use App\Http\Controllers\Property\Agent\PmTenantCreditController;
use App\Http\Controllers\Property\Agent\PmTenantDirectoryController;
use App\Http\Controllers\Property\Agent\PmVendorWebController;
use App\Http\Controllers\Property\Agent\PropertyAdvisorWebController;
use App\Http\Controllers\Property\Agent\PropertyAccountingController;
use App\Http\Controllers\Property\Agent\PropertyAmenityController;
use App\Http\Controllers\Property\Agent\PropertyCommunicationsWebController;
use App\Http\Controllers\Property\Agent\PropertyDataExportController;
use App\Http\Controllers\Property\Agent\PropertyListingsPipelineController;
use App\Http\Controllers\Property\Agent\PropertyPortfolioController;
use App\Http\Controllers\Property\Agent\PropertySettingsStoreWebController;
use App\Http\Controllers\Property\Agent\PropertyTeamUserController;
use App\Http\Controllers\Property\Agent\PropertySettingsWebController;
use App\Http\Controllers\Property\Agent\PropertyTenantsOpsWebController;
use App\Http\Controllers\Property\Agent\PropertyUtilityChargeController;
use App\Http\Controllers\Property\Agent\UtilityLedgerController;
use App\Http\Controllers\Property\Agent\UtilityAnalyticsController;
use App\Http\Controllers\Property\Agent\UtilityPeriodController;
use App\Http\Controllers\Property\Agent\PropertyReportsController;
use App\Http\Controllers\Property\Agent\RevenueController;
use App\Http\Controllers\Property\Agent\EquitySyncController;
use App\Http\Controllers\Property\Agent\FinanceDiagnosticsController;
use App\Http\Controllers\Property\Agent\AccountingReconciliationController;
use App\Http\Controllers\Property\Agent\FinanceIntegrityDashboardController;
use App\Http\Controllers\Property\Agent\FinancialReconciliationController;
use App\Http\Controllers\Property\Agent\PropertySearchController;
use App\Http\Controllers\Property\Landlord\LandlordPortalController;
use App\Http\Controllers\Property\Landlord\LandlordPortalWorkspaceController;
use App\Http\Controllers\Property\PropertyPortalQuickActionController;
use App\Http\Controllers\Property\PropertyGeoController;
use App\Http\Controllers\Property\Tenant\TenantPortalController;
use App\Http\Controllers\Property\Tenant\TenantWorkspaceFormController;
use Illuminate\Support\Facades\Route;

Route::middleware(['property.portal:landlord'])->prefix('property/landlord')->name('property.landlord.')->group(function () {
    Route::get('/portfolio', [LandlordPortalController::class, 'portfolio'])->name('portfolio');
    Route::get('/earnings', [LandlordPortalController::class, 'earnings'])->name('earnings.index');
    Route::get('/earnings/withdraw', [LandlordPortalController::class, 'withdraw'])->name('earnings.withdraw');
    Route::post('/earnings/withdraw', [LandlordPortalController::class, 'withdrawStore'])->name('earnings.withdraw.store');
    Route::get('/earnings/settings', [LandlordPortalController::class, 'payoutSettings'])->name('earnings.settings');
    Route::post('/earnings/settings', [LandlordPortalController::class, 'savePayoutSettings'])->name('earnings.settings.store');
    Route::get('/earnings/remittances', [LandlordPortalWorkspaceController::class, 'remittances'])->name('earnings.remittances');
    Route::get('/earnings/history', [LandlordPortalController::class, 'history'])->name('earnings.history');
    Route::get('/earnings/history/export', [LandlordPortalController::class, 'exportHistoryCsv'])->name('earnings.history.export');
    Route::get('/properties', [LandlordPortalController::class, 'properties'])->name('properties');
    Route::get('/properties/{property}', [LandlordPortalController::class, 'propertyShow'])->whereNumber('property')->name('properties.show');
    Route::get('/properties/export', [LandlordPortalController::class, 'exportPropertiesCsv'])->name('properties.export');
    Route::get('/reports/income', [LandlordPortalController::class, 'reportIncome'])->name('reports.income');
    Route::get('/reports/income/export', [LandlordPortalController::class, 'exportIncomeReportCsv'])->name('reports.income.export');
    Route::get('/reports/expenses', [LandlordPortalController::class, 'reportExpenses'])->name('reports.expenses');
    Route::get('/reports/expenses/export', [LandlordPortalController::class, 'exportExpensesReportCsv'])->name('reports.expenses.export');
    Route::get('/reports/cash-flow', [LandlordPortalController::class, 'reportCashFlow'])->name('reports.cash_flow');
    Route::get('/reports/statement', [LandlordPortalController::class, 'statement'])->name('reports.statement');
    Route::get('/reports/statement/export', [LandlordPortalController::class, 'exportStatementCsv'])->name('reports.statement.export');
    Route::get('/leases', [LandlordPortalWorkspaceController::class, 'leases'])->name('leases.index');
    Route::get('/reports/rent-roll', [LandlordPortalWorkspaceController::class, 'rentRoll'])->name('reports.rent_roll');
    Route::get('/reports/arrears', [LandlordPortalWorkspaceController::class, 'arrears'])->name('reports.arrears');
    Route::get('/reports/owner-statement', [LandlordPortalWorkspaceController::class, 'ownerStatement'])->name('reports.owner_statement');
    Route::get('/reports/owner-statement/pdf', [LandlordPortalWorkspaceController::class, 'exportOwnerStatementPdf'])->name('reports.owner_statement.pdf');
    Route::post('/reports/owner-statement/acknowledge', [LandlordPortalWorkspaceController::class, 'acknowledgeStatement'])->name('reports.owner_statement.acknowledge');
    Route::get('/vacancies', [LandlordPortalWorkspaceController::class, 'vacancies'])->name('vacancies');
    Route::get('/settings', [LandlordPortalWorkspaceController::class, 'settings'])->name('settings.index');
    Route::post('/settings', [LandlordPortalWorkspaceController::class, 'saveSettings'])->name('settings.store');
    Route::post('/settings/password', [LandlordPortalWorkspaceController::class, 'updatePassword'])->name('settings.password');
    Route::post('/contact-agency', [LandlordPortalWorkspaceController::class, 'contactAgency'])->name('contact_agency');
    Route::get('/maintenance/jobs/{job}', [LandlordPortalWorkspaceController::class, 'maintenanceShow'])->whereNumber('job')->name('maintenance.jobs.show');
    Route::post('/maintenance/requests', [LandlordPortalWorkspaceController::class, 'maintenanceStore'])->name('maintenance.requests.store');
    Route::get('/documents/invoices/{invoice}/pdf', [LandlordPortalWorkspaceController::class, 'invoicePdf'])->whereNumber('invoice')->name('documents.invoice');
    Route::get('/reports', [LandlordPortalWorkspaceController::class, 'reportsIndex'])->name('reports.index');
    Route::get('/maintenance', [LandlordPortalController::class, 'maintenance'])->name('maintenance');
    Route::post('/maintenance/threshold', [LandlordPortalController::class, 'saveMaintenanceThreshold'])->name('maintenance.threshold.store');
    Route::post('/maintenance/jobs/{job}/approval', [LandlordPortalController::class, 'approveMaintenanceJob'])->name('maintenance.jobs.approval');
    Route::get('/notifications', [LandlordPortalController::class, 'notifications'])->name('notifications');
    Route::post('/notifications/preferences', [LandlordPortalController::class, 'saveNotificationPreferences'])->name('notifications.preferences.store');
    Route::get('/documents', [LandlordPortalController::class, 'documents'])->name('documents');
    Route::get('/audit-trail', [LandlordPortalController::class, 'auditTrail'])->name('audit_trail');
    Route::get('/audit-trail/export', [LandlordPortalController::class, 'exportAuditTrailCsv'])->name('audit_trail.export');
    Route::get('/loans', [LandlordPortalController::class, 'loans'])->name('loans');
    Route::post('/loans/apply', [LandlordPortalController::class, 'applyLoan'])->name('loans.apply');
    Route::post('/loans/repay', [LandlordPortalController::class, 'repayLoan'])->name('loans.repay');
    Route::redirect('/opportunities', '/property/landlord/properties?view=vacancies')->name('opportunities');

    Route::get('/quick-action', function () {
        return redirect()
            ->route('property.landlord.portfolio')
            ->with('success', 'That address is for form submissions only. Use an action button on the page you came from.');
    });
    Route::post('/quick-action', [PropertyPortalQuickActionController::class, 'storeLandlord'])->name('quick_action.store');
});
