<?php

return [
    'events' => [
        'LoanDisbursed' => [
            'event_key' => 'LoanDisbursed',
            'event_name' => 'Loan Disbursed',
            'description' => 'Loan approved and money sent to client',
            'debit_slot' => 'loan_portfolio_performing_account',
            'credit_slot' => 'disbursement_cash_account',
            'risk_level' => 'high',
            'requires_approval' => true,
            'active' => true,
        ],
        'ClientPaymentReceived' => [
            'event_key' => 'ClientPaymentReceived',
            'event_name' => 'Client Payment Received',
            'description' => 'Client payment received into company collection channel',
            'debit_slot' => 'collection_cash_account',
            'credit_slot' => 'client_wallet_liability_account',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'active' => true,
        ],
        'PrincipalAllocated' => [
            'event_key' => 'PrincipalAllocated',
            'event_name' => 'Principal Allocated',
            'description' => 'Wallet funds allocated to reduce principal',
            'debit_slot' => 'client_wallet_liability_account',
            'credit_slot' => 'loan_portfolio_performing_account',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'active' => true,
        ],
        'InterestReceived' => [
            'event_key' => 'InterestReceived',
            'event_name' => 'Interest Received',
            'description' => 'Wallet funds allocated to interest income',
            'debit_slot' => 'client_wallet_liability_account',
            'credit_slot' => 'interest_income_account',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'active' => true,
        ],
        'FeeReceived' => [
            'event_key' => 'FeeReceived',
            'event_name' => 'Fee Received',
            'description' => 'Wallet funds allocated to fees income',
            'debit_slot' => 'client_wallet_liability_account',
            'credit_slot' => 'fee_income_account',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'active' => true,
        ],
        'PenaltyReceived' => [
            'event_key' => 'PenaltyReceived',
            'event_name' => 'Penalty Received',
            'description' => 'Wallet funds allocated to penalty income',
            'debit_slot' => 'client_wallet_liability_account',
            'credit_slot' => 'penalty_income_account',
            'risk_level' => 'high',
            'requires_approval' => false,
            'active' => true,
        ],
        'LoanOverpayment' => [
            'event_key' => 'LoanOverpayment',
            'event_name' => 'Loan Overpayment',
            'description' => 'Client paid more than required and balance is held as liability',
            'debit_slot' => 'collection_cash_account',
            'credit_slot' => 'client_wallet_liability_account',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'active' => true,
        ],
        'RefundIssued' => [
            'event_key' => 'RefundIssued',
            'event_name' => 'Refund Issued',
            'description' => 'Refund paid back to client from wallet/suspense',
            'debit_slot' => 'client_wallet_liability_account',
            'credit_slot' => 'collection_cash_account',
            'risk_level' => 'high',
            'requires_approval' => true,
            'active' => true,
        ],
        'ExpensePaid' => [
            'event_key' => 'ExpensePaid',
            'event_name' => 'Expense Paid',
            'description' => 'Business expense paid from operating cash',
            'debit_slot' => 'operating_expense_account',
            'credit_slot' => 'collection_cash_account',
            'risk_level' => 'medium',
            'requires_approval' => true,
            'active' => true,
        ],
        'SalaryPaid' => [
            'event_key' => 'SalaryPaid',
            'event_name' => 'Salary Paid',
            'description' => 'Staff salary paid from operating cash',
            'debit_slot' => 'salary_expense_account',
            'credit_slot' => 'collection_cash_account',
            'risk_level' => 'high',
            'requires_approval' => true,
            'active' => true,
        ],
        'SalaryAdvanceIssued' => [
            'event_key' => 'SalaryAdvanceIssued',
            'event_name' => 'Salary Advance Issued',
            'description' => 'Salary advance issued to staff',
            'debit_slot' => 'staff_advances_account',
            'credit_slot' => 'collection_cash_account',
            'risk_level' => 'high',
            'requires_approval' => true,
            'active' => true,
        ],
        'NplReclassification' => [
            'event_key' => 'NplReclassification',
            'event_name' => 'NPL Reclassification',
            'description' => 'Matured unpaid loan moved from performing to NPL',
            'debit_slot' => 'loan_portfolio_npl_account',
            'credit_slot' => 'loan_portfolio_performing_account',
            'risk_level' => 'high',
            'requires_approval' => true,
            'active' => true,
        ],
        'WriteOff' => [
            'event_key' => 'WriteOff',
            'event_name' => 'Loan Write-Off',
            'description' => 'Loan written off after approval',
            'debit_slot' => 'writeoff_expense_account',
            'credit_slot' => 'loan_portfolio_npl_account',
            'risk_level' => 'critical',
            'requires_approval' => true,
            'active' => true,
        ],
        'ReversalPosted' => [
            'event_key' => 'ReversalPosted',
            'event_name' => 'Reversal Posted',
            'description' => 'Reversal of a previously posted transaction',
            'debit_slot' => 'reversal_debit_slot',
            'credit_slot' => 'reversal_credit_slot',
            'risk_level' => 'high',
            'requires_approval' => true,
            'active' => true,
            'allow_same_account' => true,
        ],
    ],
];
