<?php

return [
    /*
     * Kenya city/town dropdown options for property forms.
     * Kept as a simple array so you can easily add/remove items without migrations.
     */
    'cities' => [
        'Nairobi',
        'Mombasa',
        'Kisumu',
        'Nakuru',
        'Eldoret',
        'Thika',
        'Malindi',
        'Kitale',
        'Garissa',
        'Kakamega',
        'Nyeri',
        'Meru',
        'Machakos',
        'Kericho',
        'Embu',
        'Nanyuki',
        'Naivasha',
        'Narok',
        'Voi',
        'Wajir',
        'Mandera',
        'Marsabit',
        'Isiolo',
        'Lamu',
        'Kilifi',
        'Kwale',
        'Taveta',
        'Taita',
        'Bungoma',
        'Busia',
        'Siaya',
        'Homa Bay',
        'Migori',
        'Kisii',
        'Nyamira',
        'Bomet',
        'Sotik',
        'Kapenguria',
        'Lodwar',
        'Maralal',
        'Chuka',
        'Kerugoya',
        'Murang’a',
        'Kiambu',
        'Kikuyu',
        'Ruiru',
        'Athi River',
        'Kajiado',
        'Ol Kalou',
        'Gilgil',
        'Limuru',
    ],
];

